version: '3'

services:
  # Redis service for job queue
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # API service with explicit context
  api:
    build:
      context: ./c3_render_api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_KEY=${API_KEY}
    depends_on:
      - redis
    restart: unless-stopped

  # Worker service with explicit context
  worker:
    build:
      context: ./c3_render_worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - C3_API_KEY=${C3_API_KEY}
      - OUTPUT_DIR=/app/output
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SECURE=${MINIO_SECURE:-false}
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
    volumes:
      - worker_output:/app/output
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      replicas: 3

volumes:
  redis_data:
  worker_output: